// Regenerates lib/src/render/embedded_templates.g.dart from templates/.
//
// Run after changing anything under templates/:
//
//   dart run tool/embed_templates.dart
//
// A test asserts the generated file matches the directory, so forgetting this
// fails CI rather than silently shipping stale templates.
//
// ## Why templates are embedded at all
//
// `dart compile exe` bundles only Dart code. In an AOT binary
// `Isolate.resolvePackageUri` returns null and there is no package directory,
// so a compiled beej cannot read templates/ from disk — it fails with
// "could not locate beej templates". Embedding them as Dart source is what
// makes a standalone binary possible, and it costs ~215 KB of string literals.

import 'dart:io';

import 'package:path/path.dart' as p;

Future<void> main() async {
  final root = Directory('templates');
  if (!root.existsSync()) {
    stderr.writeln('run this from the package root: templates/ not found');
    exit(1);
  }

  final files =
      root
          .listSync(recursive: true)
          .whereType<File>()
          .map((f) => p.relative(f.path, from: root.path).replaceAll(r'\', '/'))
          .toList()
        ..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/embed_templates.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Every file under templates/, embedded so a compiled binary')
    ..writeln('// is self-contained. Regenerate with:')
    ..writeln('//')
    ..writeln('//   dart run tool/embed_templates.dart')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    // Without this `dart format` rewraps 87 giant string literals, which both
    // churns the diff and breaks the CI check that regenerating produces no
    // change.
    ..writeln('// dart format off')
    ..writeln()
    ..writeln('/// Template path (relative to `templates/`) to its content.')
    ..writeln(
      'const Map<String, String> embeddedTemplates = <String, String>{',
    );

  var bytes = 0;
  for (final relative in files) {
    final content = File(p.join(root.path, relative)).readAsStringSync();
    bytes += content.length;
    buffer
      ..write('  ')
      ..write(_dartString(relative))
      ..write(': ')
      ..write(_dartString(content))
      ..writeln(',');
  }
  buffer.writeln('};');

  final out = File(p.join('lib', 'src', 'render', 'embedded_templates.g.dart'));
  out.writeAsStringSync(buffer.toString());

  stdout.writeln(
    'embedded ${files.length} templates '
    '(${(bytes / 1024).toStringAsFixed(0)} KB) into ${out.path}',
  );
}

/// A single-quoted Dart string literal for [value].
///
/// Escapes exactly what Dart needs: backslash, the quote, `$` (which would
/// otherwise start an interpolation), and the control characters. Non-ASCII is
/// left alone — Dart source is UTF-8, so Nepali text and em-dashes are literal.
String _dartString(String value) {
  final buffer = StringBuffer("'");
  for (final rune in value.runes) {
    switch (rune) {
      case 0x5C: // backslash
        buffer.write(r'\\');
      case 0x27: // '
        buffer.write(r"\'");
      case 0x24: // $
        buffer.write(r'\$');
      case 0x0A:
        buffer.write(r'\n');
      case 0x0D:
        buffer.write(r'\r');
      case 0x09:
        buffer.write(r'\t');
      default:
        if (rune < 0x20) {
          buffer.write('\\x${rune.toRadixString(16).padLeft(2, '0')}');
        } else {
          buffer.writeCharCode(rune);
        }
    }
  }
  return (buffer..write("'")).toString();
}
