import 'dart:io';

import 'package:path/path.dart' as p;

import '../spec/app_spec.dart';

/// Outcome of a keystore attempt.
///
/// A missing `keytool` is a normal, recoverable situation — the Gradle config
/// falls back to debug signing and the project still builds — so this reports
/// rather than throws.
sealed class KeystoreOutcome {
  const KeystoreOutcome();
}

class KeystoreCreated extends KeystoreOutcome {
  const KeystoreCreated(this.path);
  final String path;
}

class KeystoreSkipped extends KeystoreOutcome {
  const KeystoreSkipped(this.reason);
  final String reason;
}

class KeystoreFailed extends KeystoreOutcome {
  const KeystoreFailed(this.output);
  final String output;
}

/// Generates the Android release keystore and `android/key.properties`.
class KeystoreGenerator {
  const KeystoreGenerator();

  /// Create the keystore described by [spec] inside [projectDirectory].
  Future<KeystoreOutcome> generate(
    AppSpec spec, {
    required String projectDirectory,
  }) async {
    final keystore = spec.keystore;
    if (keystore == null) {
      return const KeystoreSkipped('no signing details given');
    }
    if (!spec.hasAndroid) {
      return const KeystoreSkipped('android is not a target platform');
    }

    final keytool = _findKeytool();
    if (keytool == null) {
      return const KeystoreSkipped(
        'keytool not found — install a JDK, or set JAVA_HOME. '
        'The Gradle config falls back to debug signing until then; see '
        'android/key.properties.example',
      );
    }

    final relativePath = p.join('keystore', '${spec.name}.jks');
    final absolutePath = p.join(projectDirectory, 'android', relativePath);
    Directory(p.dirname(absolutePath)).createSync(recursive: true);

    if (File(absolutePath).existsSync()) {
      return const KeystoreSkipped('a keystore already exists at that path');
    }

    final result = await Process.run(keytool, [
      '-genkeypair',
      '-v',
      '-keystore', absolutePath,
      '-keyalg', 'RSA',
      '-keysize', '2048',
      '-validity', '${keystore.validityDays}',
      '-alias', keystore.alias,
      // Passing passwords as arguments rather than on stdin: keytool's
      // interactive prompt cannot be driven reliably across platforms, and the
      // alternative is the same secret in a temp file.
      '-storepass', keystore.storePassword,
      '-keypass', keystore.keyPassword,
      '-dname', keystore.dname ?? _defaultDname(spec),
    ]);

    if (result.exitCode != 0) {
      return KeystoreFailed('${result.stderr}\n${result.stdout}'.trim());
    }

    // key.properties points at a path relative to android/, matching what the
    // generated build.gradle.kts resolves with rootProject.file().
    File(
      p.join(projectDirectory, 'android', 'key.properties'),
    ).writeAsStringSync(
      '# Release signing. Generated by beej — gitignored, never commit it.\n'
      '#\n'
      '# Back up the .jks somewhere safe. Losing it means never being able to\n'
      '# update this app on Play under the same listing again.\n'
      'storeFile=${relativePath.replaceAll(r'\', '/')}\n'
      'storePassword=${keystore.storePassword}\n'
      'keyAlias=${keystore.alias}\n'
      'keyPassword=${keystore.keyPassword}\n',
    );

    return KeystoreCreated(absolutePath);
  }

  /// X.500 name used when the spec did not supply one.
  static String _defaultDname(AppSpec spec) =>
      'CN=${spec.displayName}, O=PopupBits, C=NP';

  /// Locate `keytool`: PATH first, then JAVA_HOME, then the JBR that ships
  /// with Android Studio — which is the only JDK on many Flutter machines.
  static String? _findKeytool() {
    final exe = Platform.isWindows ? 'keytool.exe' : 'keytool';

    final onPath = _which(exe);
    if (onPath != null) return onPath;

    final candidates = <String?>[
      Platform.environment['JAVA_HOME'],
      Platform.environment['ANDROID_STUDIO_JBR'],
      if (Platform.isMacOS)
        '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
      if (Platform.isLinux) '/opt/android-studio/jbr',
      if (Platform.isWindows) r'C:\Program Files\Android\Android Studio\jbr',
    ];

    for (final home in candidates) {
      if (home == null || home.isEmpty) continue;
      final candidate = p.join(home, 'bin', exe);
      if (File(candidate).existsSync()) return candidate;
    }
    return null;
  }

  static String? _which(String command) {
    try {
      final result = Process.runSync(Platform.isWindows ? 'where' : 'which', [
        command,
      ]);
      if (result.exitCode != 0) return null;
      final first = result.stdout.toString().split('\n').first.trim();
      return first.isEmpty ? null : first;
    } catch (_) {
      return null;
    }
  }
}
